from __future__ import annotations

MAX_HISTORY_OBSERVATIONS = 10
MAX_FAILURES = 5
LOOP_DETECTION_THRESHOLD = 2
SCREENSHOT_POLL_INTERVAL_MS = 50
SCREENSHOT_POLL_TIMEOUT_MS = 2000
SCREENSHOT_STABLE_FRAMES = 3
VISION_MODEL_TIMEOUT_S = 15
PLANNER_TIMEOUT_S = 20
VISION_CONFIDENCE_HIGH = 0.8
VISION_CONFIDENCE_LOW = 0.5
MAX_PLANNER_MISPARSE_RETRIES = 3
TRANSIENT_BACKOFF_MS = 500
MAX_CONSECUTIVE_VISION_FAILURES = 3
